seed: 0
development: true
wandb: false

gpu:
  strategy: null # null for one device, fsdp2 for multiple devices

training:
  epochs: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  save_steps: 500

optimizer:
  name: muon
  learning_rate: 1.0e-3
  weight_decay: 0.05
  scheduler: cosine
  warmup_ratio: 0.03

# Which leads to use
# Corresponds to PTB-XL lead ordering
# ["I", "II", "III", "aVL", "aVR", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]
leads:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11

# ECG time length in Sampling Rate (250 Hz) * Seconds (10 sec)
segment_length: 2500

# Augmentation
augment_ecg: false

# Perturbation
perturbation: null

# Modality
modality: signal

enable_thinking: false

system_prompt_path: src/elm/config/system_prompts/think.txt

model:
  name: orah
  checkpoint: null
  # vision_model: google/siglip2-base-patch16-naflex
  vision_model: /p01/whan/ecg_encoder/src/runs/pretrain/siglip2-base-patch16-naflex/2/hf_converted
  truncation_length: 1024
  num_ecg_tokens: 100
  patch_size: 25
  trainable: [projector, language_model]
  language_model: Qwen/Qwen3.5-0.8B-Base
  peft: false
  lora_rank: 16
  lora_alpha: 32
  target_modules: all-linear
